# Site settings
title: Design At Berkeley
email: hello@designatberkeley.com
description: > # this means to ignore newlines until "baseurl:"
  The student-curated website for everything related to design at Berkeley.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://designatberkeley.com" # the base hostname & protocol for your site
twitter_username: designatcal
github_username:  shanawho

# Build settings
markdown: kramdown

defaults:
  -
    scope: 
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

prose:
  rooturl: ''
  siteurl: 'http://designatberkeley.com'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - .DS_Store
    - .gitignore
    - CNAME
    - /_sass
    - /css
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "layout"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Classes"
              value: "classes"
            - name: "Clubs"
              value: "clubs"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""